### ISSUE TITLE
process() method is deprecated

### ISSUE THREAD

**Issue by joseluisq** [nDmitry/grunt-autoprefixer#113]
Last version is [v3.0.0](https://github.com/nDmitry/grunt-autoprefixer/releases/tag/v3.0.0)

```sh
Running "autoprefixer:dist" (autoprefixer) task
Autoprefixer's process() method is deprecated and will removed in next major release. 
Use postcss([autoprefixer]).process() instead
```

**Comment by t0lkman** [comment]
confirm!

**Comment by joseluisq** [comment]
Task

```js
autoprefixer: {
  options: {
    browsers: ['> 1%', 'last 2 versions', 'Firefox ESR', 'Opera 12.1'],
    map: true,
    inline: false,
    sourcesContent: false
  },
  dist: {
    files: [{
      expand: true,
      cwd: '<%= config.app %>/',
      src: '{,*/}*.css',
      dest: '<%= config.app %>/'
    }]
  }
},
```


Output

![image](https://cloud.githubusercontent.com/assets/1700322/7848511/fbc1d00e-0491-11e5-999b-dfcf07d1a2f2.png)

**Comment by stephenbe** [comment]
+1

**Comment by AntoineBoulanger** [comment]
+1

**Comment by jillmolloy** [comment]
+1

**Comment by ai** [comment]
Just move to [grunt-postcss](https://github.com/nDmitry/grunt-postcss), because it is more official way to use Autoprefixer.

**Comment by joseluisq** [comment]
@ai Great! So this case I think you may to add to `README.md` some explaination about this and the official link to [grunt-postcss](https://github.com/nDmitry/grunt-postcss).

**Comment by ai** [comment]
@joseluisq Autoprefixer’s `README.md` has link only for grunt-postcss ;).

**Comment by joseluisq** [comment]
@ai sure 
In general, do you recommend to use `grunt-postcss` instead `grunt-autoprefixer` right?
If It's true,  Is `grunt-autoprefixer` deprecated?

**Comment by ai** [comment]
@joseluisq yeap, I recommends `grunt-postcss`.

But I can’t deprecate `grunt-autoprefixer` beause it is not my project.

**Comment by joseluisq** [comment]
@ai I understand now I will refer to [grunt-postcss](https://github.com/nDmitry/grunt-postcss) for official way.
Thanks :+1:

**Comment by ai** [comment]
@nDmitry this issue is not closed yeat, because you didn’t display `result.warnings()`.

BTW, [PostCSS Runner Guidelines](https://github.com/postcss/postcss/blob/master/docs/guidelines/runner.md) is highly recommended for Autoprefixers plugins too.

**Comment by nDmitry** [comment]
@ai do you think I should deprecate this plugin in favour of grunt-postcss?

**Comment by ai** [comment]
@nDmitry Yeap, grunt-postcss updates faster and it is better for ecosystem. And you need to maintain only one project.

**Comment by nDmitry** [comment]
@ai so be it)

**Comment by nDmitry** [comment]
Ok, guidelines are passed too.
