### ISSUE TITLE
Browser list ['> 5% in US'] throws warning

### ISSUE THREAD

**Issue by jbender** [nDmitry/grunt-autoprefixer#117]
Probably something that is actually a problem with `ai/browserlist` but this is throwing a warning in my grunt config, see the verbose output below:

    Running "autoprefixer:dist" (autoprefixer) task
    Verifying property autoprefixer.dist exists in config...OK
    Files: .tmp/styles/main.css -> .tmp/styles/main.css
    Options: cascade, diff=false, map=false, silent=false, browsers=["last 2 versions","> 5% in US"]
    Warning: Unknown browser requirement `> 5% in US` Use --force to continue.

Interestingly this is actually [used as their example](https://github.com/ai/browserslist#queries) on that page, so I'm not quite sure what's going on.

**Comment by nDmitry** [comment]
Couldn't reproduce this. From `silent` option in your output I can tell you're using an outdated plugin version, please update and try again.

**Comment by jbender** [comment]
Upgrading did the trick, should have tried that first :+1:
