### ISSUE TITLE
No "autoprefixer" targets found.

### ISSUE THREAD

**Issue by MoAnsir** [nDmitry/grunt-autoprefixer#120]
when i try to run grunt autoprefixer i get the following error
>> No "autoprefixer" targets found.
Warning: Task "autoprefixer" failed. Use --force to continue.

i used the following to install it:
npm install grunt-autoprefixer --save-dev

**Comment by ai** [comment]
`grunt-autoprefixer` was depreacted, you should use `grunt-postcss`.

**Comment by MoAnsir** [comment]
Yep postcss done it.
Found a good tutorial for getting you set up with it:
http://webdesign.tutsplus.com/tutorials/postcss-quickstart-guide-grunt-setup--cms-24545
