### ISSUE TITLE
Update autoprefixer-core to 5.0.0

### ISSUE THREAD

**Issue by matiasvad** [nDmitry/grunt-autoprefixer#90]
https://github.com/postcss/autoprefixer-core

**Comment by yisibl** [comment]
Autoprefixer 5.0 done!

https://github.com/postcss/autoprefixer/releases/tag/5.0.0

**Comment by jsw0528** [comment]
Fighting!

**Comment by alexortiz201** [comment]
Is this why I'm getting an error with cannot read property 0 of null when I updated to the most recent version? I read else where that there was an issue introduced in 3.2 or so that caused.

**Comment by yisibl** [comment]
:+1:
