### ISSUE TITLE
map.sourceContent option ignored unless map.inline:true

### ISSUE THREAD

**Issue by menzer** [nDmitry/grunt-autoprefixer#91]
**Expected behavior**: setting `map.sourceContent: false` doesn't generate `sourcesContent` in source map
**Observed behavior**: `map.sourceContent` only affects the source map file when `map.inline: true`, but the inline source map still contains `sourcesContent`

This is harmful because the `sourcesContent` output breaks variable linking.

---

I noticed that with grunt-autoprefixer running, cmd-clicking a value set by a variable no longer linked to the variable definition, and instead linked to the rule. After experimenting with various settings, I found that the sourcesContent property in the source map file seems incompatible with Chrome's variable linking. 

I set map.sourceContent:false, and found that grunt-autoprefixer was still generating source maps with sourcesContent. The only time sourcesContent seemed to work was when inline source maps were generated, which still contain the sourcesContent, and still break Chromes variable linking.

**Comment by nDmitry** [comment]
The option is source**s**Content, so there is a nasty typo in the readme (sorry). Does correct spelling solve the problem?

**Comment by menzer** [comment]
Yep, that seems to work as expected. Thanks!
