### ISSUE TITLE
No error message/fail when incorrect browsers specified

### ISSUE THREAD

**Issue by benfrain** [nDmitry/grunt-autoprefixer#92]
I had been using Autoprefixer 2.0.0 with this browser config:

```
options: {
	browsers: ['last 2 version','Android 2']
},
```

However, after updating to 2.2.0 the Autoprefixer task continued without any error messages but was not processing the job (e.g. it didn't pick up the source file and write to a dest).

It turns out that the browsers parameters I had been using in 2.0.0 are not valid for 2.2.0.

Could some feedback be included so that the task fails if an incorrect browsers parameter is passed?

**Comment by BenHaldenby** [comment]
Seconded. This has caught me out as well.

**Comment by jljorgenson18** [comment]
+1

**Comment by varemenos** [comment]
+1

**Comment by rhoffmann** [comment]
+1 (caused me some debug session, try/catched the prefix() function)
