### ISSUE TITLE
Browser list  ['Chrome', 'Safari', 'iOS', 'Firefox'] throwing warning

### ISSUE THREAD

**Issue by karthilxg** [nDmitry/grunt-autoprefixer#94]
I'm using "grunt-autoprefixer" version  "version": "0.7.6".

I have tried to use the below list of bowsers in my GruntFile, running grunt autoprefixer throws warning, however passing the option as 'last 1 version' works fine.

 // Add vendor prefixed styles
    autoprefixer: {
      options: {
        browsers: ['Chrome', 'Safari', 'iOS', 'Firefox']
      },
      dist: {
        files: [{
          expand: true,
          cwd: '.tmp/styles/',
          src: '{,*/}*.css',
          dest: '.tmp/styles/'
        }]
      }
    }
    
Running "autoprefixer:dist" (autoprefixer) task
Warning: Unknown browser requirement `Chrome` Use --force to continue.

Aborted due to warnings.

**Comment by nDmitry** [comment]
I guess you haven't specified browsers versions you want to support. More on that here: https://github.com/ai/browserslist#queries

**Comment by karthilxg** [comment]
@nDmitry  Thanks for pointing it out, updating the browser list to 'browsers: ['Chrome > 25', 'Safari > 6', 'iOS 7', 'Firefox > 25']' works fine.

**Comment by prosenjit-itobuz** [comment]
Thank you.  :)
