### ISSUE TITLE
background-image: -webkit-linear-gradient(left, #5bd8ff, #ff0000);

### ISSUE THREAD

**Issue by li2274221** [nDmitry/grunt-autoprefixer#98]
background-image: -webkit-linear-gradient(left, #5bd8ff, #ff0000);
background-image: linear-gradient(left, #5bd8ff, #ff0000);

When I run this task，I will get  'background-image: linear-gradient(left, #5bd8ff, #ff0000);'
But I need keep the css   'background-image: -webkit-linear-gradient(left, #5bd8ff, #ff0000);'
What can I do?

**Comment by nDmitry** [comment]
You should specify browsers your project supports and let Autoprefixer do the work https://github.com/nDmitry/grunt-autoprefixer#optionsbrowsers
